---
- hosts: webservers
  vars:
    globomantics_site_path: "c:\\inetpub\\wwwroot\\mynewsite"
    default_index_file: "index.html"
  tasks:
  - name: Ensure that IIS is installed
    win_feature:
      name: "Web-Server"
      state: present
      restart: no
      include_sub_features: no
      include_management_tools: no

  - name: Ensure the globomantics website directory is created
    win_file:
      path: "{{ globomantics_site_path }}"
      state: directory

  - name: Create sub iis website
    win_iis_website:
      name: "My New Site"
      state: started
      port: 8085
      physical_path: "{{ globomantics_site_path }}"

  - name: Copy default index file to site
    win_copy:
      src: "{{ default_index_file }}"
      dest: "{{ globomantics_site_path }}\\index.html"

